### ISSUE TITLE
Add support for --ignore

### ISSUE THREAD

**Issue by ralphtheninja** [pmuellr/wr#13]
Currently I'm just running wr like:

``` bash
wr 'npm test' .
```

It works fine but reacts to some temporary files created by my editor while I'm editing something, which triggers a change. I'd like to be able to tell wr about files that it shouldn't care about, e.g. by:

``` bash
wr 'npm test' --ignore='*.txt'
```

Extra sugar would be to add any number of ignore filters, like a colon separated string or whatever.

**Comment by pmuellr** [comment]
Should the operation be:
- expand full list of files we're looking at
- for all those files, for any that match an "--ignore" spec, then ignore it.

That's usually the way I think of these things working, but I might want to look at some other commands that have "include" and "exclude" processing, and see what they do (maybe like `rsync`?)

At that point, we'll need a glob matcher or a glob-to-regex converter.

And then at that point, I'll want to use the glob matcher for use in .wr files, which currently can't deal with any wild-carding.

It gets complicated, doesn't it?

Alternatively, you can list all the source files as globs from the command line (but not.wr file), like:

   wr "command-to-run" *.cc *.cpp *.h *.hpp

which wouldn't take into account anything but .cc, .cpp, .h, .hpp files.

**Comment by ralphtheninja** [comment]
It could also be a .wrignore file in the current folder. No need to have glob matcher, just start simple with regular javascript regex, i.e. /^foo/ or /js$/ and check that array of regexps against the name of the file that changed. You can even omit the slashes.
